
<%@ page language="java" import="java.util.*" pageEncoding="gbk"%>
<div id="div_footer">Co-Trip&copy;2014-2016 &nbsp;&nbsp;<script src="http://s15.cnzz.com/stat.php?id=5185942&web_id=5185942&show=pic" language="JavaScript"></script> 
  &nbsp;&nbsp;在线客服：<a href="http://wpa.qq.com/msgrd?v=3&uin=120981475&site=qq&menu=yes" target="_blank"><img src="http://wpa.qq.com/imgd?IDKEY=d6d45747ae5c725fdb770852a3fd7d29028c54cfdfdb656f&pic=51" alt="点击这里给我发消息" width="62" height="17" border="0" align="absmiddle" title="点击这里给我发消息" /></a></div>
