    <ul>
      <!-- 搜索 -->
      <li>
        <div class="side_title">
          <h3 style="margin: 0px;">&nbsp;&nbsp;search meeting</h3>
        </div>
        <div class="side_content side_font">
          <form action="main/search.jsp" method="get">
            <input class="side_font" type="text" name="searchKey" />
            <input type="submit" name="submit" value="search" />
          </form>
        </div>
      </li>
      <!-- 联系我们 -->
      <li>
        <div class="side_title">
          <h3 style="margin: 0px;">&nbsp;&nbsp;contact us</h3>
        </div>
        <div class="side_content side_font"> phone:18700000000<br />
          email:admin@cotrip.com<br />
          address:xiangtan<br />
        </div>
      </li>
      <li>
        <div class="side_title">
          <h3 style="margin: 0px;">&nbsp;&nbsp;advice</h3>
        </div>
        <div class="side_content side_font">
          <form action="#" method="get">
            <input class="side_font" type="text" name="searchKey" />
            <input type="submit" name="submit" value="submit" />
          </form>
        </div>
      </li>
    </ul>
